### ISSUE TITLE
spacemacs: Company completion in the REPL

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#64] opened 2019-03-21 23:01 UTC
I was just wondering whether there is a recommended setup to get company completion on the REPL. I see autocompletion with tab works just fine, but it'd be awesome if we could get a list of candidates at point.

Again, many thanks for this project. Any pointers are welcome and I'd be happy to help with any investigations.

**Comment by dzop** [comment] 2019-03-21 23:31
I also use `company` and I am getting a list of candidates without pressing `TAB`. What is your setting of `company-idle-delay`and `company-minimum-prefix-length`? You will also need to have the `company-capf` backend in `company-backends`, this is already present in the default value of `company-backends`.

**Comment by dangom** [comment] 2019-03-22 08:33
Sure, it must be something in my configuration. When I `C-c C-v C-z` switch-to-buffer, company mode seems to be nil. Simply calling `company-mode` does not set the backends, so the buffer local `company-backends` is also nil.

I'm using Spacemacs. I'll investigate and write back a solution, in case something stumbles upon the same issue.

**Comment by dangom** [comment] 2019-03-22 08:56
Ok, I now have the following in my config, with which company works:

```elisp
(use-package jupyter
    :config (set-face-attribute
             'jupyter-repl-traceback nil :background "wheat1")
    :ensure t
    :bind (:map jupyter-repl-mode-map
                ("C-n" . nil)
                ("C-p" . nil))
    :hook (jupyter-repl-mode . (lambda ()
                                 (company-mode)
                                 (setq company-backends '(company-capf)))))
```

**Comment by dangom** [comment] 2019-03-22 11:05
OK, so the issue must be related to Spacemacs somehow. Also for org-src-edit-special, company is not turned on.

Related: https://github.com/syl20bnr/spacemacs/issues/11893

**Comment by dzop** [comment] 2019-03-22 20:38
From the spacemacs [documentation ](https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bcompletion/auto-completion#enable-company-or-auto-complete-globally) it looks like `company` is only enabled in supported major modes which is why it doesn't work. @benneti this is probably something the spacemacs-jupyter (https://github.com/benneti/spacemacs-jupyter) layer can work on.

It also looks like `company-capf` is not a default backend used by spacemacs (at least on the `devel` branch), so you would probably have to adapt the examples in https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bcompletion/auto-completion#add-auto-completion-in-a-layer to integrate better with spacemacs.

**Comment by dzop** [comment] 2019-03-26 16:15
Closing as this is an issue with `spacemacs`.

**Closed by dzop** 2019-03-26 16:15 UTC

**Comment by benneti** [comment] 2019-03-27 13:35
I will take a look at it on the weekend

**Comment by benneti** [comment] 2019-03-27 21:45
@dangom you can try my layer now, it should work in the REPL now.
In org mode it should have worked all along as `company-capf` is loaded there by default.

@dzop Could you imagine a reason why in `org-mode` the completion does not work the first time I open an org file?
If I go in the corresponding src-block wait for the kernel to start, kill the buffer and open the file again the completion works and there is no error.

**Comment by dzop** [comment] 2019-03-28 03:35
@benneti Not sure. The source block completion works when `jupyter-org-interaction-mode` is enabled which adds the function `jupyter-org-completion-at-point` to `completion-at-point-functions`. So a first step to finding the problem is to ensure that `jupyter-org-interaction-mode` is in `org-mode-hook` and that `jupyter-org-completion-at-point` is in `completion-at-point-functions`. Then you can set `jupyter--debug` to `t`, type normally, and maybe press `TAB` a few times to see if completion requests are actually being sent by examining the messages printed in the `*Messages*` buffer.

**Comment by benneti** [comment] 2019-03-28 20:38
Yeah the problem is that the `jupyter-org-interaction-mode` mode is not loaded the first time I open an org file but it is in the `org-mode-hook`.
Manually executing it works fine, too.

Here is the `*Messages*` buffer content
```
[yas] Prepared just-in-time loading of snippets successfully.
Loading /home/benneti/.emacs.d/.cache/company-statistics-cache.el (source)...done
Loading /home/benneti/.emacs.d/elpa/26.1/develop/julia-mode-20190111.2044/julia-latexsubs...done
Shell native completion is disabled, using fallback
START: nil
START-CHANNEL: (:shell)
START-CHANNEL: (:iopub)
START-CHANNEL: (:stdin)
Starting python3 kernel process...done
MESSAGE: (:iopub :status (:execution_state starting))
RUN-HOOK: jupyter-iopub-message-hook
Kernel starting up...done
SENDING: :kernel-info-request nil
SENT: (:shell b1ba18bd-cc5a-442c-b477-be7233bd0815)
MESSAGE: (:iopub :status (:execution_state busy))
MESSAGE: (:shell :kernel-info-reply (:status ok :protocol_version 5.1 :implementation ipython :implementation_version 7.3.0 :language_info (:name python :version 3.7.2 :mimetype text/x-python :codemirror_mode (:name ipython :version 3) :pygments_lexer ipython3 :nbconvert_exporter python :file_extension .py) :banner Python 3.7.2 (default, Jan 10 2019, 23:51:51)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.3.0 -- An enhanced Interactive Python. Type '?' for help.
 :help_links [(:text Python Reference :url https://docs.python.org/3.7) (:text IPython Reference :url https://ipython.org/documentation.html) (:text NumPy Reference :url https://docs.scipy.org/doc/numpy/reference/) (:text SciPy Reference :url https://docs.scipy.org/doc/scipy/reference/) (:text Matplotlib Reference :url https://matplotlib.org/contents.html) (:text SymPy Reference :url http://docs.sympy.org/latest/index.html) (:text pandas Reference :url https://pandas.pydata.org/pandas-docs/stable/)]))
Requesting kernel info...done
Can’t guess python-indent-offset, using defaults: 4
SENDING: :history-request (:output :json-false :raw :json-false :hist_access_type tail :n 100)
SENDING: :execute-request (:code  :silent t :store_history t :user_expressions #s(hash-table size 1 test eql rehash-size 1.5 rehash-threshold 0.8125 data ()) :allow_stdin t :stop_on_error :json-false)
MESSAGE: (:iopub :status (:execution_state idle))
SENT: (:shell 710d171f-683b-461c-b295-5c0444b106d3)
SENT: (:shell df34d20b-df33-478c-9039-70daafddf90a)
DROPPING-REQ: b1ba18bd-cc5a-442c-b477-be7233bd0815
MESSAGE: (:iopub :status (:execution_state busy))
MESSAGE: (:iopub :status (:execution_state idle))
DROPPING-REQ: 710d171f-683b-461c-b295-5c0444b106d3
MESSAGE: (:shell :history-reply (:status ok :history [[358 1 import sys;print ('\n'.join(sys.path))] [360 1 import numpy as np
[... lots of source code ...]
 :cursor_pos 72)
SENT: (:shell 8a61b464-76ff-497c-af94-90f0d8d54380)
MESSAGE: (:iopub :status (:execution_state busy))
DROPPING-REQ: 93e5684d-fb2f-4f22-bc98-c31daac3ec78
MESSAGE: (:shell :complete-reply (:matches [isinstance issubclass] :cursor_end 72 :cursor_start 70 :metadata (:_jupyter_types_experimental [(:start 70 :end 72 :text isinstance :type function) (:start 70 :end 72 :text issubclass :type function)]) :status ok))
MESSAGE: (:iopub :status (:execution_state idle))
```

**Comment by benneti** [comment] 2019-03-28 21:14
Ah I think the problem is that I add jupyter to the babel languages enclosed by a 
`(with-eval-after-load 'org ...)`
But I think this is necessary as spacemacs doesn't use the org-mode shipping with emacs and therefore configuring it before the correct one is loaded gives rise to problems.
See http://spacemacs.org/layers/+emacs/org/README.html#important-note.

**Comment by dzop** [comment] 2019-03-28 21:36
`jupyter-org-interaction-mode` is added to `org-mode-hook` when loading `jupyter-org-client.el` at the following line

https://github.com/dzop/emacs-jupyter/blob/c3e67281f1ec4ca3049aa26b62151275c496aea9/jupyter-org-client.el#L626

so maybe `org-mode` has already been called before `org-babel-do-load-languages`? But I think all the code in a `with-eval-after-load` form gets loaded *before* `org-mode` is called. What you can do is, before opening an `org-mode` file, evaluate

```emacs-lisp
(defun b/check-org-mode-hook ()
  (message "org-mode-hook: %s" org-mode-hook)
  (backtrace))

(add-hook 'org-mode-hook 'b/check-org-mode-hook)
```

then open an `org-mode` file and show what you got in the `*Messages*` buffer. This way we can get a better idea of the execution path that happens and the value of `org-mode-hook` on the first call to `org-mode`.

**Comment by benneti** [comment] 2019-03-28 21:58
Yeah this confirms that it is only added the second time I open an org file.
I do not really understand why this is the case, as adding other hooks in the `with-eval-after-load` works.
Just to be sure adding the babel language should also load `jupyter-org-client.el` so I don't need to do anything additionally?

**Comment by dzop** [comment] 2019-03-28 22:11
Yes, `(org-babel-do-load-languages ...)` will call `(require 'ob-jupyter)` and `ob-jupyter` will load `jupyter-org-client.el`. It seems like the `org-babel-do-load-languages` is being called after the first call to `org-mode`? That's the only situation that I can think of right now that would cause this behavior.

**Comment by benneti** [comment] 2019-03-28 22:13
Yeah I came to the same conclusion.
I think the spacemacs loading system does this as it usually is sufficient to load the languages there but it seems `org-babel-do-load-languages` should be called at least once during the startup.
I got it working now thank you!

**Comment by moritzschaefer** [comment] 2022-12-26 20:51
@benneti would you mind sharing the link to the readme you are referring to? I experience the same issues described here.

**Comment by benneti** [comment] 2022-12-26 22:19
Sorry I don't know anymore, but probably the spacemacs layer for org or Jupiter from 3 years ago.
