### ISSUE TITLE
The :file header argument sometimes does not work.

### ISSUE THREAD

**Issue by dangom** [dzop/emacs-jupyter#16] opened 2019-01-26 15:13 UTC
Steps to reproduce:

1. Open *scratch* buffer
2. Create a jupy-python src block with the following contents:

```
#+begin_src jupy-python :file garbage.png :session foo
import matplotlib.pyplot as plt
plt.plot([1,2,3])
#+end_src
```

3. Execute block with C-c C-c
See results showing up empty:
```
#+RESULTS:
```

4. Press C-c C-c again.
See file `garbage.png` showing up.

5. Change plotting code and re-execute block:
```
plt.plot([1,4,3])
```
Image does not update. If I retry executing the block after some time, then the plot will eventually update.

Sometimes during the process I get the following error:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  (let* ((link-path (org-element-property :path (org-element-context))) (link-dir (expand-file-name (file-name-directory link-path))) (resource-dir (expand-file-name org-babel-jupyter-resource-directory))) (if (and (equal link-dir resource-dir) (file-exists-p link-path)) (progn (delete-file link-path))))
  (while (re-search-forward link-re bound t) (let* ((link-path (org-element-property :path (org-element-context))) (link-dir (expand-file-name (file-name-directory link-path))) (resource-dir (expand-file-name org-babel-jupyter-resource-directory))) (if (and (equal link-dir resource-dir) (file-exists-p link-path)) (progn (delete-file link-path)))))
  (let ((bound (org-babel-result-end))) (while (re-search-forward link-re bound t) (let* ((link-path (org-element-property :path (org-element-context))) (link-dir (expand-file-name (file-name-directory link-path))) (resource-dir (expand-file-name org-babel-jupyter-resource-directory))) (if (and (equal link-dir resource-dir) (file-exists-p link-path)) (progn (delete-file link-path))))))
  (save-excursion (goto-char result-pos) (forward-line) (let ((bound (org-babel-result-end))) (while (re-search-forward link-re bound t) (let* ((link-path (org-element-property :path (org-element-context))) (link-dir (expand-file-name (file-name-directory link-path))) (resource-dir (expand-file-name org-babel-jupyter-resource-directory))) (if (and (equal link-dir resource-dir) (file-exists-p link-path)) (progn (delete-file link-path)))))))
  (if link-re (save-excursion (goto-char result-pos) (forward-line) (let ((bound (org-babel-result-end))) (while (re-search-forward link-re bound t) (let* ((link-path (org-element-property :path (org-element-context))) (link-dir (expand-file-name (file-name-directory link-path))) (resource-dir (expand-file-name org-babel-jupyter-resource-directory))) (if (and (equal link-dir resource-dir) (file-exists-p link-path)) (progn (delete-file link-path))))))))
  (let* ((result-pos (and t (org-babel-where-is-src-block-result))) (link-re (and result-pos (format "^[ \011]*%s[ \011]*$" org-bracket-link-regexp)))) (if link-re (save-excursion (goto-char result-pos) (forward-line) (let ((bound (org-babel-result-end))) (while (re-search-forward link-re bound t) (let* ((link-path (org-element-property :path (org-element-context))) (link-dir (expand-file-name (file-name-directory link-path))) (resource-dir (expand-file-name org-babel-jupyter-resource-directory))) (if (and (equal link-dir resource-dir) (file-exists-p link-path)) (progn (delete-file link-path)))))))))
  org-babel-jupyter-cleanup-file-links()
  (progn (org-babel-jupyter-cleanup-file-links))
  (if (member "replace" (assq :result-params params)) (progn (org-babel-jupyter-cleanup-file-links)))
  (let* ((jupyter-current-client (save-current-buffer (set-buffer (org-babel-jupyter-initiate-session (alist-get :session params) params)) jupyter-current-client)) (kernel-lang (jupyter-kernel-language jupyter-current-client)) (vars (org-babel-variable-assignments:jupyter params kernel-lang)) (code (org-babel-expand-body:jupyter body params vars kernel-lang)) (req (progn (eieio-oset jupyter-current-client 'block-params params) (jupyter-send-execute-request jupyter-current-client :code code)))) (if (member "replace" (assq :result-params params)) (progn (org-babel-jupyter-cleanup-file-links))) (cond ((or (equal (alist-get :async params) "yes") (plist-member params :async)) (if (progn (or (and (memq (type-of req) cl-struct-jupyter-org-request-tags) t) (signal 'wrong-type-argument (list 'jupyter-org-request req))) (aref req 12)) "" (jupyter-org-insert-async-id req))) (t (jupyter-wait-until-idle req most-positive-fixnum) (if (progn (or (and (memq (type-of req) cl-struct-jupyter-org-request-tags) t) (signal 'wrong-type-argument (list 'jupyter-org-request req))) (aref req 12)) (car (progn (or (and (memq (type-of req) cl-struct-jupyter-org-request-tags) t) (signal 'wrong-type-argument (list 'jupyter-org-request req))) (aref req 9))) (prog1 (jupyter-org-sync-results req) (nconc (alist-get :result-params params) (list "raw")))))))
  org-babel-execute:jupy-python("import matplotlib.pyplot as plt\nplt.plot([1,4,3])" ((:colname-names) (:rowname-names) (:result-params "file" "replace") (:result-type . value) (:results . "file replace") (:exports . "both") (:session . "ipython") (:cache . "no") (:kernel . "python3") (:noweb . "no") (:hlines . "no") (:tangle . "no") (:eval . "never-export") (:file . "garbage.png")))
  org-babel-execute-src-block(nil ("jupy-python" "import matplotlib.pyplot as plt\nplt.plot([1,4,3])" ((:colname-names) (:rowname-names) (:result-params "file" "replace") (:result-type . value) (:results . "file replace") (:exports . "both") (:file . "garbage.png") (:eval . "never-export") (:tangle . "no") (:hlines . "no") (:noweb . "no") (:kernel . "python3") (:cache . "no") (:session . "ipython")) "" nil 1 "(ref:%s)"))
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  call-interactively(org-ctrl-c-ctrl-c nil nil)
  command-execute(org-ctrl-c-ctrl-c)
```

**Comment by dzop** [comment] 2019-01-26 22:14
Nice catch! I will look into this. The error you got is an easy fix.

It does look like the plot doesn't show on the first execution of that code, but I'm wondering if this is an IPython issue. Could you set `jupyter--debug` to `t` and then do the exact some process with a fresh session and everything. The `jupyter--debug` variable will print the messages that Emacs receives from the kernel to the `*Messages*` buffer, the messages from the kernel will be prefixed with `MESSAGE:`.

Whenever I did this and ran the code block the first time, the messages returned from the kernel did not show a `:display-data` message but on the second run they did. The `:display-data` message is what the kernel sends to Emacs whenever you call `plt.plot` to show the actual plot.

**Comment by dzop** [comment] 2019-01-27 01:00
It doesn't. If you remove the :file parameter there still won't be a `:display-data` message on the first run. But then you will run into another bug that I found and fixed with the latest master.

All that is sent to the kernel is the code of the code block. See the following https://github.com/dzop/emacs-jupyter/blob/ee1078d0c7dc5478ae8797f40e7c21a01a38b6d1/ob-jupyter.el#L248-L254

I think the issue about the `:display-data` message not showing up the first time has to do with needing to specify `%matplotlib inline` (see https://ipython.readthedocs.io/en/stable/interactive/plotting.html#id1) before calling `plot`. I was able to get it working with

```python
#+begin_src jupy-python :file garbage.png
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot([1,2,3])
#+end_src
```
Everything should be fixed by the latest master, let me know if it isn't.

**Comment by dzop** [comment] 2019-02-13 01:06
I can't reproduce this. If I delete the `.ob-jupyter` directory and run

```python
#+begin_src jupy-python :file garbage.png
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot([1,2,3])
#+end_src
```

it always creates a file named `garbage.png` and doesn't create a random file in the `.ob-jupyter` directory. Could you provide a sample source block and steps to reproduce the problem?

**Comment by dangom** [comment] 2019-02-14 22:25
I've just tried the codeblock you've proposed above with the latest master of jupyter and latest master of zmq. I also deleted the .ob-jupyter directory.

For me, steps to reproduce:

1. Start emacs and toggle debug on error
2. Scratch buffer and paste the following:
```python
#+begin_src jupyter-python :file garbage.png
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot([1,2,3])
#+end_src
```
3. `C-c C-c` to execute block
4. Get following backtrace:
```
Debugger entered--Lisp error: (search-failed "b1f525c7-3dbf-4a05-8d0f-6b92d6db2db2")
  re-search-forward("b1f525c7-3dbf-4a05-8d0f-6b92d6db2db2")
  (save-current-buffer (set-buffer buffer) (goto-char (point-min)) (re-search-forward sentinel) (re-search-backward "\\(call\\|src\\)_\\|^[ \011]*#\\+\\(BEGIN_SRC\\|CALL:\\)") (org-babel-remove-result) (org-babel-insert-result (ob-ipython--process-response ret file result-type) (cdr (assoc :result-params (nth 2 (org-babel-get-src-block-info))))) (org-redisplay-inline-images))
  (with-current-buffer buffer (goto-char (point-min)) (re-search-forward sentinel) (re-search-backward "\\(call\\|src\\)_\\|^[ \011]*#\\+\\(BEGIN_SRC\\|CALL:\\)") (org-babel-remove-result) (org-babel-insert-result (ob-ipython--process-response ret file result-type) (cdr (assoc :result-params (nth 2 (org-babel-get-src-block-info))))) (org-redisplay-inline-images))
  (save-restriction (with-current-buffer buffer (goto-char (point-min)) (re-search-forward sentinel) (re-search-backward "\\(call\\|src\\)_\\|^[ \011]*#\\+\\(BEGIN_SRC\\|CALL:\\)") (org-babel-remove-result) (org-babel-insert-result (ob-ipython--process-response ret file result-type) (cdr (assoc :result-params (nth 2 (org-babel-get-src-block-info))))) (org-redisplay-inline-images)))
  (save-excursion (save-restriction (with-current-buffer buffer (goto-char (point-min)) (re-search-forward sentinel) (re-search-backward "\\(call\\|src\\)_\\|^[ \011]*#\\+\\(BEGIN_SRC\\|CALL:\\)") (org-babel-remove-result) (org-babel-insert-result (ob-ipython--process-response ret file result-type) (cdr (assoc :result-params (nth 2 (org-babel-get-src-block-info))))) (org-redisplay-inline-images))))
  (progn (save-excursion (save-restriction (with-current-buffer buffer (goto-char (point-min)) (re-search-forward sentinel) (re-search-backward "\\(call\\|src\\)_\\|^[ \011]*#\\+\\(BEGIN_SRC\\|CALL:\\)") (org-babel-remove-result) (org-babel-insert-result (ob-ipython--process-response ret file result-type) (cdr (assoc :result-params (nth 2 (org-babel-get-src-block-info))))) (org-redisplay-inline-images)))))
  (unwind-protect (progn (save-excursion (save-restriction (with-current-buffer buffer (goto-char (point-min)) (re-search-forward sentinel) (re-search-backward "\\(call\\|src\\)_\\|^[ \011]*#\\+\\(BEGIN_SRC\\|CALL:\\)") (org-babel-remove-result) (org-babel-insert-result (ob-ipython--process-response ret file result-type) (cdr (assoc :result-params (nth 2 (org-babel-get-src-block-info))))) (org-redisplay-inline-images))))) (set-window-configuration wconfig))
  (let ((wconfig (current-window-configuration))) (unwind-protect (progn (save-excursion (save-restriction (with-current-buffer buffer (goto-char (point-min)) (re-search-forward sentinel) (re-search-backward "\\(call\\|src\\)_\\|^[ \011]*#\\+\\(BEGIN_SRC\\|CALL:\\)") (org-babel-remove-result) (org-babel-insert-result (ob-ipython--process-response ret file result-type) (cdr (assoc :result-params (nth 2 (org-babel-get-src-block-info))))) (org-redisplay-inline-images))))) (set-window-configuration wconfig)))
  (save-window-excursion (save-excursion (save-restriction (with-current-buffer buffer (goto-char (point-min)) (re-search-forward sentinel) (re-search-backward "\\(call\\|src\\)_\\|^[ \011]*#\\+\\(BEGIN_SRC\\|CALL:\\)") (org-babel-remove-result) (org-babel-insert-result (ob-ipython--process-response ret file result-type) (cdr (assoc :result-params (nth 2 (org-babel-get-src-block-info))))) (org-redisplay-inline-images)))))
  (lambda (ret sentinel buffer file result-type) (when nil (setf (cdr (assoc :display (assoc :result ret))) (-filter (lambda (el) (memq (car el) 'nil)) (cdr (assoc :display (assoc :result ret))))) (setf (cdr (assoc :value (assoc :result ret))) (-filter (lambda (el) (memq (car el) 'nil)) (cdr (assoc :value (assoc :result ret)))))) (save-window-excursion (save-excursion (save-restriction (with-current-buffer buffer (goto-char (point-min)) (re-search-forward sentinel) (re-search-backward "\\(call\\|src\\)_\\|^[ \011]*#\\+\\(BEGIN_SRC\\|CALL:\\)") (org-babel-remove-result) (org-babel-insert-result (ob-ipython--process-response ret file result-type) (cdr (assoc :result-params (nth 2 (org-babel-get-src-block-info))))) (org-redisplay-inline-images))))))(((:result (:value (text/plain . "[<matplotlib.lines.Line2D at 0x119771dd8>]")) (:display (text/plain . "<Figure size 432x288 with 1 Axes>") (image/png . "iVBO++ GIGANTIC STRING HERE++...ErkJggg==\n"))) (:output . "") (:data) (:exec-count . 8)) "b1f525c7-3dbf-4a05-8d0f-6b92d6db2db2" #<buffer *scratch*> nil value))
  #f(compiled-function (G739 G740 proc state) #<bytecode 0x45862479>)(--args-- --callback-- #<process execute> "finished\n")
  apply(#f(compiled-function (G739 G740 proc state) #<bytecode 0x45862479>) --args-- --callback-- (#<process execute> "finished\n"))
  (lambda (&rest --cl-rest--) (apply (function #f(compiled-function (G739 G740 proc state) #<bytecode 0x45862479>)) '--args-- '--callback-- --cl-rest--))(#<process execute> "finished\n")
```

I'm a bit out of time now, but I'll try to investigate this a bit further to see if I can figure out what's going on.

**Comment by dzop** [comment] 2019-02-14 22:33
Based on the traceback, the src-block is is going through `ob-ipython`. It is probably because you still have `ipython` in your `org-babel-load-languages` and we now use the `jupyter-` prefix for src-blocks which `ob-ipython` also uses. If you run

```
(org-babel-jupyter-aliases-from-kernelspecs)
```

you should be able to override `ob-ipython` and use `emacs-jupyter` instead.

**Comment by dangom** [comment] 2019-02-14 22:59
Indeed. The call to `(org-babel-jupyter-aliases-from-kernelspecs)` solves the ob-ipython issue.
Now I do get the figures, but they're still in the .ob-jupyter directory, and not with the filename that I specified. Here's the codeblock and results:
```python
#+begin_src jupyter-python :file garbage.png :session foo
import matplotlib.pyplot as plt
%matplotlib inline
plt.plot([1,2,3])
#+end_src

#+RESULTS:
:RESULTS:
| <matplotlib.lines.Line2D | at | 0x11afd9518> |
[[file:./.ob-jupyter/a9fb336335342d3cbb94585cd212c8a03451a1d1.png]]
:END:
```

**Comment by stardiviner** [comment] 2019-02-14 23:32
Try specify babel header argument  `:dir`

**Comment by GregorySchwartz** [comment] 2019-02-20 17:20
I am also getting this issue where `:file` is ignored no matter what (following all the steps in this issue). I get an image, but it's always a random `png` filename in `./ob-jupyter`. This is problematic as I need `svg` outputs.

**Comment by dzop** [comment] 2019-02-20 19:14
OK, I think I have found the problem of the original issue. `org-mode` does some special handling of the `:file` parameter which is temporarily suppressed and it looks like the results are being received before we put that information back.

About the svg vs png, you should get a random svg file name if the results are svg and a random png file if the results are png. If you evaluate `(setq jupyter--debug t)` you should see something like the following in the `*Messages*` buffer and you can verify if you are getting png data

```
MESSAGE: (:iopub :display-data (:data (:text/plain <Figure size 432x288 with 1 Axes> :image/png ...) :metadata (:needs_background light) :transient nil))
```

if you have svg you should see `:image/svg+xml` instead of `:image/png`.

**Comment by GregorySchwartz** [comment] 2019-02-20 19:32
@dzop Yes, you are correct, it does work with the `svg` with `%config` setting `svg` in the python kernel. For the `haskell` kernel, however, the option `:option svg` does not result in an `svg`. It works in the browser notebook, though.

For no `:option no-svg`:

```
MESSAGE: (:iopub :display-data (:data (:image/png iVBORw0 ...
```

For `:option svg`:

```
MESSAGE: (:iopub :display-data (:data (:text/html <img src="data:image/svg+xml;base64,PD94bWwg ... Zz4K"/> :image/png iVBORw0KGg ...
```

**Comment by dzop** [comment] 2019-02-20 19:51
It looks like the haskell kernel is giving an svg image embedded in html which is why you are seeing only png. I think it would be better to ask the people who make the Haskell kernel to provide an image/svg+xml representation of their images before doing anything on this side. Both the IPython and IJulia provide an svg representation and according to the Jupyter spec the `display-data` messages should contain all representations of the data. Also it would be best to make a new issue for this since I have not really considered the Haskell kernel, I've only been testing with IJulia and IPython.

Regarding the original issue about only getting random file names when `:file` is specified, does the latest master fix the issue?

**Comment by dzop** [comment] 2019-03-07 17:18
@dangom Do you still experience issues on the latest master?

**Comment by dangom** [comment] 2019-03-07 18:42
Nope. As far as I can tell, the issue is gone!

Thank you again for this awesome project.

**Closed** 2019-03-07 18:55 UTC
Labels: bug
