### ISSUE TITLE
text/html displayed too small

### ISSUE THREAD

**Issue by non-Jedi** [dzop/emacs-jupyter#4] opened 2018-11-06 19:03 UTC
Since `jupyter--debug` doesn't seem to log incoming requests (can't look at the metadata associated with svg myself), I haven't been able to get very far in debugging this myself. You're a julia user, so I'll give repro steps in terms of julia code (and an image to let you see what I'm talking about).

```julia
using Pkg; Pkg.add.(("Gadfly", "RDatasets"));
using Gadfly, RDatasets;
df = dataset("datasets", "iris")
plot(df, x=:SepalLength, y=:SepalWidth)
```

![jupyter-emacs-small-svg](https://user-images.githubusercontent.com/17915621/48087112-6fcbb800-e1cc-11e8-87a7-5d837dbebae9.png)

**Comment by dzop** [comment] 2018-11-08 17:08
I can confirm this. The issue is that the `plot` call returns both `text/html` and `image/svg+xml` but the function which inserts the message data, `jupyter-repl-insert-data`, prioritizes `text/html` over `image/svg+xml`. To insert html I use the `shr` library and it looks like it's default handling of images is not sufficient for our case.

In the meantime, you can make the priority of `image/svg+xml` higher than `text/html` by moving its `cond` clause above `text/html` in `jupyter-repl-insert-data`. I will write a `shr-put-image-function` that will insert the image properly.

**Comment by dzop** [comment] 2018-11-17 21:47
OK I believe I have fixed this by parsing as XML if an XML prolog is given, i.e. if the `text/html` results start with something like `<?xml version="1.0" encoding="UTF-8"?>` and parsing as HTML otherwise.

Let me know if this is still an issue.

**Closed** 2018-12-11 03:47 UTC
